name-template: "$name (version v$NEXT_PATCH_VERSION)"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "💣 Breaking Change"
    label: "Breaking Change"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🔨 Maintenance"
    labels:
      - "devops"
      - "maintenance"
  - title: "📝 Documentation"
    label: "documentation"
change-template: "- #$NUMBER: $TITLE "
template: |
  ## What' new

  Welcome to the $name release of BC Registries authentication and authorization services. \
  There are a number of updates in this version that we hope you will like, some of the key highlights include:

  $CHANGES

  ## Thanks to

  $CONTRIBUTORS
