name: Auth API BUILD CI

on:
  push:
    branches:
      - gh-test

jobs:
  auth-api-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login ${{ secrets.OPENSHIFT_REGISTRY }} -u ${{ secrets.OPENSHIFT_SA_NAME}} --password-stdin
      - name: Build image
        working-directory: ./auth-api
        run: docker pull ${{ secrets.OPENSHIFT_REGISTRY }}/d7eovc-tools/python:3.7
      - uses: vrutkovs/action-s2i@master
        with:
          base: ${{ secrets.OPENSHIFT_REGISTRY }}/d7eovc-tools/python:3.7
          image: auth-api-gh:latest
