name: Auth API BUILD CI

on:
  push:
    branches:
      - development
    paths:
      - "auth-api/**"

jobs:
  auth-api-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: vrutkovs/action-s2i@master
        with:
          base: rhscl/python-37-rhel7
          image: auth-api:latest
