name: Auth API BUILD CI

on:
  push:
    branches:
      - gh-test

jobs:
  auth-api-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - uses: vrutkovs/action-s2i@master
        with:
          base: rhscl/python-37-rhel7
          image: auth-api:latest
