name: Auth API BUILD CI

on:
  push:
    branches:
      - gh-test

env:
  IMAGE_NAME: auth-api-gh
  TAG_NAME: dev

jobs:
  auth-api-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.OPENSHIFT_TOKEN }}" | docker login ${{ secrets.OPENSHIFT_REGISTRY }} -u ${{ secrets.OPENSHIFT_SA_NAME}} --password-stdin
      - name: Build image
        working-directory: ./auth-api
        run: docker pull ${{ secrets.OPENSHIFT_REGISTRY }}/d7eovc-tools/python:3.7
      - uses: vrutkovs/action-s2i@master
        with:
          base: ${{ secrets.OPENSHIFT_REGISTRY }}/d7eovc-tools/python:3.7
          image: $IMAGE_NAME:latest
      - name: Push image
        working-directory: ./auth-api
        run: |
          IMAGE_ID=${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_REPOSITORY }}/$IMAGE_NAME
          docker push ${{ secrets.OPENSHIFT_REGISTRY }}/${{ secrets.OPENSHIFT_REPOSITORY }}/$IMAGE_NAME:latest
          docker image tag $IMAGE_ID:latest $IMAGE_ID:$TAG_NAME
          docker push $IMAGE_ID:$TAG_NAME
