name: Draft release

on:
  push:
    branches:
      - master

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%B, %Y')"
      - uses: release-drafter/release-drafter@v5
        with:
          name: "${{ steps.date.outputs.date }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
