#When do we want to deploy to Test environment
name: PR label check

on:
  pull_request:
    types: [opened, synchronize, review_requested]
    branches:
      - development

jobs:
  pr-label-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jesusvasquez333/verify-pr-label-action@v1.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "bug, enhancement, feature, fix, devops, documentation, maintenance"
