name: Deployment to Test PR CI

on:
  pull_request:
    branches:
      - gh-test
      - development

  schedule:
    - cron: "*/5 * * * *"

jobs:
  test-pr:
    if: not contains(github.event.label.name, 'Do Not Merge') && new Date().addHours(0.5) < github.event.pull_request.created_at
    runs-on: ubuntu-latest
    steps:
      - name: Show current Date/time
        run: echo new Date().addHours(0.5)

  test-pr-merge:
    if: not contains(github.event.label.name, 'Do Not Merge') && new Date().addHours(0.5) > github.event.pull_request.created_at
    runs-on: ubuntu-latest
    steps:
      - name: Show PR Create Date/time
        run: echo github.event.pull_request.created_at
