name: Pre Release

on:
  release:
    types: [published, edited, released]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    if: "github.event.release.prerelease"
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $pre-release
        env:
          pre-release: ${{github.event.release.prerelease}}
