name: Pre Release

on:
  release:
    types: [published, edited, released]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
      - name: print env1
        run: echo 123
