name: test action

on: push

jobs:
  setup-job:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: test command
        run: |
          lsb_release -a
          oc --version
